name: Gitea Actions Test

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Hello World
        run: echo "Hello from Gitea Actions!"
      
      - name: Show environment
        run: |
          echo "Runner: $RUNNER_NAME"
          echo "Event: $GITHUB_EVENT_NAME"
          echo "Ref: $GITHUB_REF"
          pwd
          ls -la
